USE [CUN_REPOSITORIO]
GO

SELECT [NUM_IDENTIFICACION]
      ,[NOM_LARGO]
      ,[COD_UNIDAD]
      ,[NOM_UNIDAD]
      ,[COD_PENSUM]
      ,[COD_MATERIA]
      ,[NOM_MATERIA]
      ,[DOC_DOCENTE]
      ,[NOM_DOCENTE]
      ,[FEC_INI_PROGRAMACION]
      ,[FEC_FIN_PROGRAMACION]
      ,[DIA]
      ,[HORA_INICIAL]
      ,[HORA_FINAL]
      ,[NOM_AULA]
  FROM [CUN].[Horarios]

GO

SELECT *
FROM CUN_REPOSITORIO.CUN.Horarios
WHERE NUM_IDENTIFICACION = '1033694145';
